# deploy:
#      mode: replicated
#      replicas: 6

services:
  tor1:
    image: dockurr/tor
    container_name: tor3
    volumes:
      - ./tor/config3:/etc/tor
      - ./tor/data/tor3:/var/lib/tor
    restart: always
    networks:
      - proxy_net

  tor2:
    image: dockurr/tor
    container_name: tor2
    volumes:
      - ./tor/config2:/etc/tor
      - ./tor/data/tor2:/var/lib/tor
    restart: always
    networks:
      - proxy_net

  tor3:
    image: dockurr/tor
    container_name: tor1
    volumes:
      - ./tor/config1:/etc/tor
      - ./tor/data/tor1:/var/lib/tor
    restart: always
    networks:
      - proxy_net

  privoxy1:
    image: lusky3/privoxy:latest
    container_name: privoxy1
    volumes:
      - ./privoxy/config1:/etc/privoxy/config
    depends_on:
      - tor1
    restart: unless-stopped
    networks:
      - proxy_net

  privoxy2:
    image: lusky3/privoxy:latest
    container_name: privoxy2
    volumes:
      - ./privoxy/config2:/etc/privoxy/config
    depends_on:
      - tor2
    restart: unless-stopped
    networks:
      - proxy_net

  privoxy3:
    image: lusky3/privoxy:latest
    container_name: privoxy3
    volumes:
      - ./privoxy/config3:/etc/privoxy/config
    depends_on:
      - tor3
    restart: unless-stopped
    networks:
      - proxy_net

  nginx:
    image: nginx:alpine
    container_name: nginx_privoxy_lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8889:8888"
    depends_on:
      - privoxy1
      - privoxy2
      - privoxy3
    restart: always
    networks:
      - proxy_net


volumes:
  obfs4-data:

networks:
  proxy_net: